<a href="https://colab.research.google.com/github/jeswanth1212/dev/blob/main/loan_status_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Load CSV into a variable
data = pd.read_csv('train.csv')
dataa=pd.read_csv('test.csv')
# Display the first few rows of the DataFrame
data.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,RENT,0.0,EDUCATION,B,6000,11.49,0.17,N,14,0
1,1,22,56000,OWN,6.0,MEDICAL,C,4000,13.35,0.07,N,2,0
2,2,29,28800,OWN,8.0,PERSONAL,A,6000,8.90,0.21,N,10,0
3,3,30,70000,RENT,14.0,VENTURE,B,12000,11.11,0.17,N,5,0
4,4,22,60000,RENT,2.0,MEDICAL,A,6000,6.92,0.10,N,3,0

In [ ]:
value_counts = data['person_home_ownership'].value_counts()

# Display the value counts
print(value_counts)

person_home_ownership
RENT        30594
MORTGAGE    24824
OWN          3138
OTHER          89
Name: count, dtype: int64

In [ ]:
value_counts = data['loan_intent'].value_counts()

# Display the value counts
print(value_counts)

loan_intent
EDUCATION            12271
MEDICAL              10934
PERSONAL             10016
VENTURE              10011
DEBTCONSOLIDATION     9133
HOMEIMPROVEMENT       6280
Name: count, dtype: int64

In [ ]:
value_counts = data['loan_grade'].value_counts()

# Display the value counts
print(value_counts)

loan_grade
A    20984
B    20400
C    11036
D     5034
E     1009
F      149
G       33
Name: count, dtype: int64

In [ ]:
value_counts = data['cb_person_default_on_file'].value_counts()

# Display the value counts
print(value_counts)

cb_person_default_on_file
N    49943
Y     8702
Name: count, dtype: int64

In [ ]:
categorical_cols = ['person_home_ownership', 'loan_intent', 'loan_grade', 'cb_person_default_on_file']

# Perform one-hot encoding
data = pd.get_dummies(data, columns=categorical_cols, drop_first=True)

# Display the first few rows of the encoded DataFrame
data.head()

,id,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,loan_status,person_home_ownership_OTHER,...,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,loan_grade_B,loan_grade_C,loan_grade_D,loan_grade_E,loan_grade_F,loan_grade_G,cb_person_default_on_file_Y
0,0,37,35000,0.0,6000,11.49,0.17,14,0,False,...,False,False,False,True,False,False,False,False,False,False
1,1,22,56000,6.0,4000,13.35,0.07,2,0,False,...,True,False,False,False,True,False,False,False,False,False
2,2,29,28800,8.0,6000,8.90,0.21,10,0,False,...,False,True,False,False,False,False,False,False,False,False
3,3,30,70000,14.0,12000,11.11,0.17,5,0,False,...,False,False,True,True,False,False,False,False,False,False
4,4,22,60000,2.0,6000,6.92,0.10,3,0,False,...,True,False,False,False,False,False,False,False,False,False

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           58645 non-null  int64
 1   person_age                   58645 non-null  int64
 2   person_income                58645 non-null  int64
 3   person_emp_length            58645 non-null  float64
 4   loan_amnt                    58645 non-null  int64
 5   loan_int_rate                58645 non-null  float64
 6   loan_percent_income          58645 non-null  float64
 7   cb_person_cred_hist_length   58645 non-null  int64
 8   loan_status                  58645 non-null  int64
 9   person_home_ownership_OTHER  58645 non-null  bool
 10  person_home_ownership_OWN    58645 non-null  bool
 11  person_home_ownership_RENT   58645 non-null  bool
 12  loan_intent_EDUCATION        58645 non-null  bool
 13  loan_intent_HOMEIMPROVEMENT  58645 non-null  bool
 14  loan_intent_MEDICAL          58645 non-null  bool
 15  loan_intent_PERSONAL         58645 non-null  bool
 16  loan_intent_VENTURE          58645 non-null  bool
 17  loan_grade_B                 58645 non-null  bool
 18  loan_grade_C                 58645 non-null  bool
 19  loan_grade_D                 58645 non-null  bool
 20  loan_grade_E                 58645 non-null  bool
 21  loan_grade_F                 58645 non-null  bool
 22  loan_grade_G                 58645 non-null  bool
 23  cb_person_default_on_file_Y  58645 non-null  bool
dtypes: bool(15), float64(3), int64(6)
memory usage: 4.9 MB

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split,accuracy,accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# Load the dataset

# Data preprocessing
# (Handle missing values, encode categorical variables, scale features)

# Split the dataset
X = data.drop('loan_status', axis=1)  # Features
y = data['loan_status']  # Target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model training
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Evaluation
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

ImportError: cannot import name 'accuracy' from 'sklearn.model_selection' (/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/__init__.py)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import OneHotEncoder  # For encoding categorical variables
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
X = data.drop('loan_status', axis=1)  # Features
y = data['loan_status']
numeric_features = ['person_age', 'person_income', 'person_emp_length', 'loan_amnt', 'loan_int_rate', 'loan_percent_income','cb_person_cred_hist_length']
categorical_features = ['person_home_ownership', 'loan_intent','loan_grade','cb_person_default_on_file']
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median'))
])
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant',fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])
model = Pipeline(steps=[('preprocessor', preprocessor),
                        ('classifier', RandomForestClassifier())])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.95

In [ ]:
data.head()

,id,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,loan_status
0,0,37,35000,RENT,0.0,EDUCATION,B,6000,11.49,0.17,N,14,0
1,1,22,56000,OWN,6.0,MEDICAL,C,4000,13.35,0.07,N,2,0
2,2,29,28800,OWN,8.0,PERSONAL,A,6000,8.90,0.21,N,10,0
3,3,30,70000,RENT,14.0,VENTURE,B,12000,11.11,0.17,N,5,0
4,4,22,60000,RENT,2.0,MEDICAL,A,6000,6.92,0.10,N,3,0

In [ ]:
test_data = pd.read_csv('test.csv')  # Make sure this CSV contains the necessary columns for prediction

# Assuming the test data has an 'id' column and all necessary feature columns for predictions
# Extract features for prediction
X_test = test_data.drop('id', axis=1)  # Drop 'id' column, keeping only feature columns

# Make predictions
y_pred = model.predict(X_test)

# Create a DataFrame to store results
results = pd.DataFrame({
    'id': test_data['id'],  # Including the 'id' column
    'loan_status': y_pred
        })

        # Save results to a new CSV file
results.to_csv('predictions.csv', index=False)  # Save without index
print("Predictions saved to predictions.csv")

Predictions saved to predictions.csv